# -*- coding: utf-8 -*-
"""AI_Researcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAPLaI36LOMNsj3wAgVs7tCnuDgnwGM4
"""

!pip install pdfplumber
!pip install transformers
!pip install nltk

import pdfplumber
import re
import nltk
from nltk.tokenize import sent_tokenize

nltk.download('punkt')

"""# New Section"""

import pdfplumber
import re
from transformers import pipeline

pip install --upgrade transformers sentence-transformers

import nltk
from nltk.tokenize import sent_tokenize
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource

!pip install pdfplumber transformers nltk

import pdfplumber
import re
import nltk
from nltk.tokenize import sent_tokenize
from transformers import pipeline

nltk.download('punkt')
nltk.download('punkt_tab')

from google.colab import files
uploaded = files.upload()

#Extract text
text = ""

with pdfplumber.open("paper.pdf") as pdf:
    for page in pdf.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"

print(text[:500])

#Basic cleaning text

clean_text = " ".join(text.split())
clean_text = clean_text.lower()

print(clean_text[:500])

#Advance cleaning text

def clean_text_advanced(text: str) -> str:
    # Remove page numbers like "Page 12"
    text = re.sub(r'\bpage\s*\d+\b', '', text, flags=re.IGNORECASE)

    # Remove standalone numbers
    text = re.sub(r'\b\d+\b', '', text)

    # Remove common headers/footers
    headers_footers = ["confidential", "report", "draft", "footertext"]
    for hf in headers_footers:
        text = re.sub(rf'\b{hf}\b', '', text, flags=re.IGNORECASE)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text)

    # Remove special characters
    text = re.sub(r'[^\w\s.,;:!?-]', '', text)

    return text.strip()

# Apply adv cleaning

cleaned_text = clean_text_advanced(clean_text)

print(cleaned_text[:500])

# Optional: NLTK based summarization (if needed, otherwise remove)
def summarize_text_nltk(text: str, max_sentences=3) -> str:
    sentences = sent_tokenize(text)
    return " ".join(sentences[:max_sentences])

summary_nltk = summarize_text_nltk(cleaned_text)
print(summary_nltk)

!pip install --upgrade transformers

# New package code
# from transformers import pipeline

# abstractive_summarizer = pipeline(
#     "summarization",
#     model="facebook/bart-large-cnn"
# )

# def abstractive_summary(text):
#     return abstractive_summarizer(
#         text[:1024],
#         max_length=150,
#         min_length=50,
#         do_sample=False
#     )[0]["summary_text"]



from transformers import pipeline

abstractive_summarizer = pipeline(
    task="text-generation",
    model="facebook/bart-large-cnn",
    tokenizer="facebook/bart-large-cnn"
)

def abstractive_summary(text):
    return abstractive_summarizer(
        text[:1024],
        max_length=150,
        min_length=50,
        do_sample=False
    )[0]["generated_text"]

# generate an abstractive summary of long text by condensing it into a shorter, human-like summary using a pretrained transformer model (BART)

import pdfplumber

full_text = ""

with pdfplumber.open("paper.pdf") as pdf:
    for page in pdf.pages:
        full_text += page.extract_text() + "\n"

print(full_text[:1000])

summary = summarize_text(full_text[:300])  # limit for testing
print(summary)

print(model.config)

!pip install fastapi pydantic pymupdf faiss-cpu numpy sentence-transformers uvicorn

from fastapi import FastAPI, UploadFile, File, BackgroundTasks, HTTPException
from pydantic import BaseModel
import fitz
import uuid
import os
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from typing import List, Dict, Any
import json

print("All imports successful ✅")

import fastapi
print(fastapi.__version__)

import os

DATA_DIR = "data"
INDEX_DIR = "index"

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(INDEX_DIR, exist_ok=True)

EMBED_MODEL_NAME = "all-mpnet-base-v2"
EMBED_DIM = 768
TOP_K = 5

# sets up required directories and configuration parameters for storing data, vector indexes, and embeddings used in semantic search and retrieval.

# Initialize services

!pip install faiss-cpu

from sentence_transformers import SentenceTransformer
import faiss
from fastapi import FastAPI
from typing import Dict, Any

# Load SBERT embedding model
embed_model = SentenceTransformer(EMBED_MODEL_NAME)

# Create FAISS index (Flat L2 = Euclidean distance)
index = faiss.IndexFlatL2(EMBED_DIM)

# Metadata store: vector_id → metadata
metadata_store: Dict[int, Dict[str, Any]] = {}

# Counter for vector IDs
next_vector_id = 0

# Initialize FastAPI app
app = FastAPI(title="Research Paper Summarizer API")

# initializes the core backend services to generate embeddings, store and search them efficiently using FAISS,
# and expose the functionality through a FastAPI-based research paper summarization API.

!pip install fastapi
!pip install "uvicorn[standard]"
!pip install pydantic
!pip install pymupdf
!pip install faiss-cpu
!pip install numpy
!pip install sentence-transformers
!pip install nltk
!pip install transformers

!pip install faiss-cpu

embed_model = SentenceTransformer(EMBED_MODEL_NAME)

# FAISS index
index = faiss.IndexFlatL2(EMBED_DIM)

# Metadata store
metadata_store: Dict[int, Dict[str, Any]] = {}
next_vector_id = 0

# FastAPI app
app = FastAPI(title="Research Paper Summarizer API")

# Summarizer
# summarizer = pipeline("text2text-generation", model="facebook/bart-large-cnn")

print("Initialization complete ✅")

# initializes all core components (embedding model, FAISS index, metadata store, and FastAPI app)
# required to run the research paper summarization and retrieval system.

# Utilities
# Utilities

def extract_text_from_pdf(path: str) -> str:
    doc = fitz.open(path)
    pages = []
    for page in doc:
        text = page.get_text("text")
        pages.append(text)
    return "\n\n".join(pages)


def chunk_text(text: str, max_tokens: int = 500, overlap: int = 100) -> List[str]:
    chunks = []
    start = 0
    text_len = len(text)

    while start < text_len:
        end = min(start + max_tokens, text_len)
        chunk = text[start:end]
        chunks.append(chunk.strip())
        start = end - overlap

        if start < 0:
            start = 0
        if start >= text_len:
            break

    return [c for c in chunks if len(c) > 50]

    # Simple chunker by characters approximating tokens
# extracts raw text from PDFs and splits it into overlapping,
# manageable chunks so the content can be efficiently embedded and processed by NLP models.

def chunk_text(text: str, max_tokens: int = 500, overlap: int = 100) -> List[str]:
    chunks = []
    start = 0
    text_len = len(text)

    while start < text_len:
        end = min(start + max_tokens, text_len)
        chunk = text[start:end]
        chunks.append(chunk.strip())
        start = end - overlap

        if start < 0:
            start = 0
        if start >= text_len:
            break

    return [c for c in chunks if len(c) > 50]


def embed_texts(texts: List[str]) -> np.ndarray:
    embs = embed_model.encode(
        texts,
        convert_to_numpy=True,
        show_progress_bar=False
    )
    return embs


def persist_index():
    faiss.write_index(index, os.path.join(INDEX_DIR, "faiss.index"))
    with open(os.path.join(INDEX_DIR, "metadata.json"), "w", encoding="utf-8") as f:
        json.dump(metadata_store, f)


def load_index():
    global index, metadata_store, next_vector_id

    idx_path = os.path.join(INDEX_DIR, "faiss.index")
    meta_path = os.path.join(INDEX_DIR, "metadata.json")

    if os.path.exists(idx_path):
        index = faiss.read_index(idx_path)

    if os.path.exists(meta_path):
        with open(meta_path, "r", encoding="utf-8") as f:
            metadata_store = json.load(f)

        next_vector_id = max([int(k) for k in metadata_store.keys()]) + 1 if metadata_store else 0

# breaks large text into overlapping chunks, converts those chunks into vector embeddings,
# and saves or reloads the FAISS index with metadata so semantic search data persists across runs.

# -----------------------------------
# LLM CALL (PLACEHOLDER FUNCTION)
# -----------------------------------
# replace this with your LLM text output
# this function is a placeholder for now
# later you can integrate OpenAI / HuggingFace / any LLM

# LLM call placeholder
def call_llm(system_prompt: str, user_prompt: str) -> str:
    return "LLM_RESPONSE_PLACEHOLDER\n\n" + user_prompt[:1000]

# Background ingestion

def ingest_pdf(file_path: str, paper_id: str):
    global next_vector_id

    # Step 1: Extract text from PDF
    text = extract_text_from_pdf(file_path)

    # Step 2: Split text into chunks
    chunks = chunk_text(text, max_tokens=3000, overlap=300)

    # Step 3: Convert chunks into embeddings
    embeddings = embed_texts(chunks)

    # Step 4: Store embeddings and metadata
    for i, emb in enumerate(embeddings):

        vec_id = next_vector_id

        # Add embedding to index
        index.add(np.expand_dims(emb, axis=0))

        # Store metadata
        metadata_store[str(vec_id)] = {
            "paper_id": paper_id,
            "chunk_index": i,
            "text": chunks[i][:2000]
        }

        next_vector_id += 1

    # Step 5: Save index permanently
    persist_index()

# API models

class SummarizeRequest(BaseModel):
    paper_id: str
    length: str = "short"   # short, medium, long


class InsightRequest(BaseModel):
    paper_id: str
    questions: List[str] = []

# summarize Endpoint

@app.post("/upload")
async def upload_pdf(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...)
):
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(
            status_code=400,
            detail="Only PDF files are supported"
        )

    paper_id = str(uuid.uuid4())
    save_path = os.path.join(DATA_DIR, f"{paper_id}.pdf")

    with open(save_path, "wb") as f:
        content = await file.read()
        f.write(content)

    background_tasks.add_task(ingest_pdf, save_path, paper_id)

    return {
        "paper_id": paper_id,
        "status": "ingestion_started"
    }

@app.post("/summarize")
def summarize(req: SummarizeRequest):

    # retrieve top chunks for the paper

    # build a retrieval query: embed a short prompt
    query_text = "Summarize the main contributions of the paper"

    q_emb = embed_texts([query_text])[0]

    D, I = index.search(np.expand_dims(q_emb, axis=0), TOP_K)

    retrieved = []

    for idx in I[0]:
        meta = metadata[idx]

        if meta["paper_id"] == req.paper_id:
            retrieved.append(meta["text"])

    if not retrieved:
        return {"error": "No content found for paper_id"}

    # build prompt for LLM

    system_prompt = "You are an expert research assistant. Produce a concise summary."

    user_prompt = f"""Paper chunks:\n\n{chr(10).join(retrieved)}

Please produce a {req.length} summary with:
Abstract, Key findings, Methods, Limitations.
"""

    llm_out = call_llm(system_prompt, user_prompt)

    return {"summary": llm_out}

#Insights API
@app.post("/insights")
def insights(req: InsightRequest):

    # For each question, retrieve relevant chunks and ask LLM

    results = {}

    for q in req.questions:

        q_emb = embed_texts([q])[0]

        D, I = index.search(np.expand_dims(q_emb, axis=0), TOP_K)

        retrieved = []

        for idx in I[0]:

            meta = metadata[idx]

            if meta["paper_id"] == req.paper_id:
                retrieved.append(meta["text"])

        if not retrieved:
            results[q] = "No relevant content found"
            continue

        system_prompt = "You are a research assistant. Answer the question based on the paper."

        user_prompt = f"""Paper chunks:

{chr(10).join(retrieved)}

Question:
{q}
"""

        llm_out = call_llm(system_prompt, user_prompt)

        results[q] = llm_out

    return results





#     if meta and meta["paper_id"] == req.paper_id:
#         retrieved.append(meta["text"])

# prompt = f"Context:\n{chr(10).join(retrieved)}\n\nQuestion: {q}\nAnswer concisely and cite which chunk index supports the answer."

# ans = call_llm("Research assistant", prompt)

# results[q] = ans

# return {"insights": results}



# 1️⃣ Imports
# 2️⃣ FastAPI app
# 3️⃣ DATA_DIR
# 4️⃣ embed_texts()
# 5️⃣ call_llm()
# 6️⃣ ingest_pdf()

# 7️⃣ /upload       ← You already wrote

# 8️⃣ /summarize    ← Paste above code

# 9️⃣ /insights     ← Paste above code

from pyngrok import ngrok
import subprocess
import time

# Kill all existing tunnels
ngrok.kill()
subprocess.run(["pkill", "-9", "-f", "ngrok"], capture_output=True)
subprocess.run(["pkill", "-9", "-f", "uvicorn"], capture_output=True)
time.sleep(4)
print("✅ All cleared!")

!pip install pyngrok uvicorn -q

from pyngrok import ngrok
import uvicorn

ngrok.set_auth_token("3Ajtb2xgc9p1aGsY31Gf3yhbjgi_7QakLtYz6nzRALdfyWxL8")  # ← replace with real token
backend_url = ngrok.connect(8000)
print("🔗 Copy this URL:", backend_url.public_url)

uvicorn.run(app, host="0.0.0.0", port=8000)

# You will see something like:
# ```
# 🔗 Copy this URL: https://abc123.ngrok-free.app

!pip install streamlit pdfplumber openai pyngrok -q

"""After reinstalling the `transformers` library, we need to re-initialize the summarizer pipeline. You might need to restart your Colab runtime after the installation is complete for the changes to take full effect (Runtime -> Restart runtime)."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pdfplumber
# import openai
# import os
# import time
# 
# # paste the entire app.py code here
# 
# # ─── Page Config ────────────────────────────────────────────────────────────
# st.set_page_config(
#     page_title="ResearchAI",
#     page_icon="🔬",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # ─── Custom CSS ─────────────────────────────────────────────────────────────
# st.markdown("""
# <style>
# @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700;900&family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@300;400;500&display=swap');
# 
# :root {
#     --bg:        #0a0a0f;
#     --surface:   #12121a;
#     --card:      #1a1a26;
#     --border:    #2a2a3d;
#     --accent:    #e8c547;
#     --accent2:   #7c6af5;
#     --text:      #e8e8f0;
#     --muted:     #7a7a9a;
#     --success:   #4ecb8d;
# }
# 
# /* Global */
# html, body, [class*="css"] {
#     font-family: 'IBM Plex Sans', sans-serif;
#     background-color: var(--bg) !important;
#     color: var(--text) !important;
# }
# 
# /* Hide Streamlit default elements */
# #MainMenu, footer, header { visibility: hidden; }
# .block-container { padding-top: 2rem !important; max-width: 1200px; }
# 
# /* Sidebar */
# section[data-testid="stSidebar"] {
#     background: var(--surface) !important;
#     border-right: 1px solid var(--border) !important;
# }
# section[data-testid="stSidebar"] * { color: var(--text) !important; }
# 
# /* Hero Header */
# .hero {
#     text-align: center;
#     padding: 3rem 1rem 2rem;
#     border-bottom: 1px solid var(--border);
#     margin-bottom: 2rem;
# }
# .hero-title {
#     font-family: 'Playfair Display', serif;
#     font-size: 3.5rem;
#     font-weight: 900;
#     color: var(--accent);
#     letter-spacing: -1px;
#     line-height: 1.1;
#     margin: 0;
# }
# .hero-sub {
#     font-family: 'IBM Plex Mono', monospace;
#     font-size: 0.8rem;
#     color: var(--muted);
#     letter-spacing: 3px;
#     text-transform: uppercase;
#     margin-top: 0.5rem;
# }
# 
# /* Cards */
# .card {
#     background: var(--card);
#     border: 1px solid var(--border);
#     border-radius: 12px;
#     padding: 1.5rem;
#     margin-bottom: 1.5rem;
# }
# .card-title {
#     font-family: 'IBM Plex Mono', monospace;
#     font-size: 0.7rem;
#     letter-spacing: 2px;
#     text-transform: uppercase;
#     color: var(--accent);
#     margin-bottom: 0.75rem;
#     display: flex;
#     align-items: center;
#     gap: 0.5rem;
# }
# .card-body {
#     font-size: 0.95rem;
#     line-height: 1.8;
#     color: var(--text);
# }
# 
# /* Stat pills */
# .stat-row {
#     display: flex;
#     gap: 1rem;
#     flex-wrap: wrap;
#     margin-bottom: 1.5rem;
# }
# .stat-pill {
#     background: var(--surface);
#     border: 1px solid var(--border);
#     border-radius: 999px;
#     padding: 0.4rem 1rem;
#     font-family: 'IBM Plex Mono', monospace;
#     font-size: 0.75rem;
#     color: var(--muted);
# }
# .stat-pill span { color: var(--accent); font-weight: 500; }
# 
# /* Upload zone */
# .upload-zone {
#     border: 2px dashed var(--border);
#     border-radius: 16px;
#     padding: 3rem;
#     text-align: center;
#     background: var(--surface);
#     transition: border-color 0.2s;
# }
# .upload-zone:hover { border-color: var(--accent2); }
# 
# /* Buttons */
# .stButton > button {
#     background: var(--accent) !important;
#     color: #0a0a0f !important;
#     font-family: 'IBM Plex Mono', monospace !important;
#     font-weight: 500 !important;
#     font-size: 0.8rem !important;
#     letter-spacing: 1px !important;
#     border: none !important;
#     border-radius: 8px !important;
#     padding: 0.6rem 1.5rem !important;
#     cursor: pointer !important;
#     transition: opacity 0.2s !important;
# }
# .stButton > button:hover { opacity: 0.85 !important; }
# 
# /* Text input & text area */
# .stTextInput > div > div > input,
# .stTextArea > div > div > textarea {
#     background: var(--surface) !important;
#     border: 1px solid var(--border) !important;
#     border-radius: 8px !important;
#     color: var(--text) !important;
#     font-family: 'IBM Plex Sans', sans-serif !important;
# }
# .stTextInput > div > div > input:focus,
# .stTextArea > div > div > textarea:focus {
#     border-color: var(--accent2) !important;
#     box-shadow: 0 0 0 2px rgba(124,106,245,0.2) !important;
# }
# 
# /* Select box */
# .stSelectbox > div > div {
#     background: var(--surface) !important;
#     border: 1px solid var(--border) !important;
#     border-radius: 8px !important;
#     color: var(--text) !important;
# }
# 
# /* Tab styling */
# .stTabs [data-baseweb="tab-list"] {
#     background: var(--surface) !important;
#     border-radius: 10px !important;
#     padding: 4px !important;
#     gap: 4px !important;
#     border: 1px solid var(--border) !important;
# }
# .stTabs [data-baseweb="tab"] {
#     background: transparent !important;
#     color: var(--muted) !important;
#     font-family: 'IBM Plex Mono', monospace !important;
#     font-size: 0.75rem !important;
#     letter-spacing: 1px !important;
#     border-radius: 7px !important;
#     padding: 0.5rem 1rem !important;
# }
# .stTabs [aria-selected="true"] {
#     background: var(--card) !important;
#     color: var(--accent) !important;
# }
# 
# /* Expander */
# .streamlit-expanderHeader {
#     background: var(--card) !important;
#     border: 1px solid var(--border) !important;
#     border-radius: 8px !important;
#     color: var(--text) !important;
#     font-family: 'IBM Plex Mono', monospace !important;
#     font-size: 0.8rem !important;
# }
# 
# /* Spinner */
# .stSpinner > div { border-top-color: var(--accent) !important; }
# 
# /* Divider */
# hr { border-color: var(--border) !important; }
# 
# /* Answer box */
# .answer-box {
#     background: linear-gradient(135deg, var(--card), var(--surface));
#     border: 1px solid var(--accent2);
#     border-left: 4px solid var(--accent);
#     border-radius: 12px;
#     padding: 1.5rem;
#     font-size: 0.95rem;
#     line-height: 1.9;
#     color: var(--text);
#     margin-top: 1rem;
# }
# 
# /* Badge */
# .badge {
#     display: inline-block;
#     background: rgba(232,197,71,0.15);
#     border: 1px solid var(--accent);
#     color: var(--accent);
#     font-family: 'IBM Plex Mono', monospace;
#     font-size: 0.65rem;
#     letter-spacing: 1px;
#     text-transform: uppercase;
#     padding: 0.2rem 0.6rem;
#     border-radius: 4px;
#     margin-right: 0.4rem;
# }
# 
# /* Success message */
# .success-msg {
#     background: rgba(78,203,141,0.1);
#     border: 1px solid var(--success);
#     border-radius: 8px;
#     padding: 0.75rem 1rem;
#     color: var(--success);
#     font-family: 'IBM Plex Mono', monospace;
#     font-size: 0.8rem;
#     margin-bottom: 1rem;
# }
# 
# /* Scrollbar */
# ::-webkit-scrollbar { width: 6px; }
# ::-webkit-scrollbar-track { background: var(--bg); }
# ::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
# </style>
# """, unsafe_allow_html=True)
# 
# 
# # ─── Helper Functions ────────────────────────────────────────────────────────
# def extract_text_from_pdf(pdf_file):
#     text = ""
#     with pdfplumber.open(pdf_file) as pdf:
#         for page in pdf.pages:
#             t = page.extract_text()
#             if t:
#                 text += t + "\n"
#     return text
# 
# 
# def ask_ai(client, prompt, system_msg="You are an expert AI research assistant."):
#     response = client.chat.completions.create(
#         model="gpt-3.5-turbo",
#         messages=[
#             {"role": "system", "content": system_msg},
#             {"role": "user", "content": prompt}
#         ],
#         max_tokens=1000,
#         temperature=0.4
#     )
#     return response.choices[0].message.content
# 
# 
# # ─── Sidebar ─────────────────────────────────────────────────────────────────
# with st.sidebar:
#     st.markdown("""
#     <div style='padding: 1rem 0 0.5rem;'>
#         <div style='font-family: Playfair Display, serif; font-size: 1.4rem; color: #e8c547; font-weight: 700;'>ResearchAI</div>
#         <div style='font-family: IBM Plex Mono, monospace; font-size: 0.65rem; color: #7a7a9a; letter-spacing: 2px; text-transform: uppercase;'>Configuration</div>
#     </div>
#     <hr style='border-color: #2a2a3d; margin: 0.5rem 0 1rem;'/>
#     """, unsafe_allow_html=True)
# 
#     api_key = st.text_input("OpenAI API Key", type="password", placeholder="sk-...")
# 
#     st.markdown("<br>", unsafe_allow_html=True)
#     st.markdown("""
#     <div style='font-family: IBM Plex Mono, monospace; font-size: 0.7rem; color: #7a7a9a; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 0.5rem;'>Features</div>
#     """, unsafe_allow_html=True)
# 
#     st.markdown("""
#     <div style='font-size: 0.85rem; color: #7a7a9a; line-height: 2;'>
#     📄 PDF Extraction<br>
#     🔬 Paper Summary<br>
#     💡 Key Insights<br>
#     ❓ Q&A Chat<br>
#     📊 Methodology Analysis<br>
#     📝 Citation Generator
#     </div>
#     """, unsafe_allow_html=True)
# 
#     st.markdown("<hr style='border-color: #2a2a3d; margin: 1rem 0;'>", unsafe_allow_html=True)
#     st.markdown("""
#     <div style='font-family: IBM Plex Mono, monospace; font-size: 0.65rem; color: #3a3a5a;'>
#     Upload any research paper PDF<br>and let AI do the heavy lifting.
#     </div>
#     """, unsafe_allow_html=True)
# 
# 
# # ─── Main Content ─────────────────────────────────────────────────────────────
# st.markdown("""
# <div class='hero'>
#     <div class='hero-title'>Research AI</div>
#     <div class='hero-sub'>AI-Powered Academic Paper Analysis</div>
# </div>
# """, unsafe_allow_html=True)
# 
# # Upload section
# st.markdown("""
# <div class='card-title'>📂 &nbsp;Upload Research Paper</div>
# """, unsafe_allow_html=True)
# 
# uploaded_file = st.file_uploader(
#     "Drop your PDF here",
#     type=["pdf"],
#     label_visibility="collapsed"
# )
# 
# # ─── Processing ───────────────────────────────────────────────────────────────
# if uploaded_file:
#     if not api_key:
#         st.markdown("""
#         <div style='background: rgba(124,106,245,0.1); border: 1px solid #7c6af5; border-radius: 8px; padding: 0.75rem 1rem; color: #7c6af5; font-family: IBM Plex Mono, monospace; font-size: 0.8rem;'>
#         ⚠️  Please enter your OpenAI API key in the sidebar to enable AI features.
#         </div>
#         """, unsafe_allow_html=True)
# 
#     # Extract text
#     with st.spinner("Extracting text from PDF..."):
#         full_text = extract_text_from_pdf(uploaded_file)
#         word_count = len(full_text.split())
#         char_count = len(full_text)
#         page_estimate = max(1, char_count // 2000)
# 
#     st.markdown(f"""
#     <div class='success-msg'>✓ &nbsp;Paper loaded successfully</div>
#     <div class='stat-row'>
#         <div class='stat-pill'>Words: <span>{word_count:,}</span></div>
#         <div class='stat-pill'>Characters: <span>{char_count:,}</span></div>
#         <div class='stat-pill'>Est. Pages: <span>~{page_estimate}</span></div>
#         <div class='stat-pill'>File: <span>{uploaded_file.name}</span></div>
#     </div>
#     """, unsafe_allow_html=True)
# 
#     # ─── Tabs ───────────────────────────────────────────────────────────────
#     tab1, tab2, tab3, tab4, tab5 = st.tabs([
#         "SUMMARY", "KEY INSIGHTS", "Q&A CHAT", "METHODOLOGY", "RAW TEXT"
#     ])
# 
#     # ── Tab 1: Summary ───────────────────────────────────────────────────────
#     with tab1:
#         st.markdown("<br>", unsafe_allow_html=True)
#         if st.button("Generate Summary", key="btn_summary"):
#             if not api_key:
#                 st.error("API key required.")
#             else:
#                 client = openai.OpenAI(api_key=api_key)
#                 with st.spinner("Analyzing paper..."):
#                     summary = ask_ai(
#                         client,
#                         f"Provide a comprehensive summary of this research paper. Include: title, authors (if visible), main objective, methodology overview, key findings, and conclusions.\n\nPaper text:\n{full_text[:4000]}",
#                         "You are an expert academic researcher. Write clear, structured summaries."
#                     )
#                 st.markdown(f"""
#                 <div class='card'>
#                     <div class='card-title'>📋 &nbsp;Paper Summary</div>
#                     <div class='card-body'>{summary}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#     # ── Tab 2: Key Insights ──────────────────────────────────────────────────
#     with tab2:
#         st.markdown("<br>", unsafe_allow_html=True)
#         if st.button("Extract Key Insights", key="btn_insights"):
#             if not api_key:
#                 st.error("API key required.")
#             else:
#                 client = openai.OpenAI(api_key=api_key)
#                 with st.spinner("Extracting insights..."):
#                     insights = ask_ai(
#                         client,
#                         f"Extract the 5-7 most important insights, findings, and contributions from this paper. Format each as a clear, standalone insight with a short title and explanation.\n\nPaper:\n{full_text[:4000]}",
#                         "You are an expert at distilling complex research into clear, actionable insights."
#                     )
#                 st.markdown(f"""
#                 <div class='card'>
#                     <div class='card-title'>💡 &nbsp;Key Insights</div>
#                     <div class='card-body'>{insights}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#         st.markdown("<br>", unsafe_allow_html=True)
#         if st.button("Generate Citation", key="btn_cite"):
#             if not api_key:
#                 st.error("API key required.")
#             else:
#                 client = openai.OpenAI(api_key=api_key)
#                 with st.spinner("Generating citation..."):
#                     citation = ask_ai(
#                         client,
#                         f"Generate APA, MLA, and BibTeX citations for this paper based on the text provided. If exact details aren't clear, make reasonable inferences.\n\nPaper:\n{full_text[:2000]}",
#                         "You are an academic citation expert."
#                     )
#                 st.markdown(f"""
#                 <div class='card'>
#                     <div class='card-title'>📝 &nbsp;Citations</div>
#                     <div class='card-body' style='font-family: IBM Plex Mono, monospace; font-size: 0.85rem;'>{citation}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#     # ── Tab 3: Q&A ───────────────────────────────────────────────────────────
#     with tab3:
#         st.markdown("<br>", unsafe_allow_html=True)
#         st.markdown("""
#         <div class='card-title'>❓ &nbsp;Ask Anything About This Paper</div>
#         """, unsafe_allow_html=True)
# 
#         # Initialize chat history
#         if "messages" not in st.session_state:
#             st.session_state.messages = []
# 
#         # Display chat history
#         for msg in st.session_state.messages:
#             role_icon = "🧑" if msg["role"] == "user" else "🤖"
#             role_color = "#7c6af5" if msg["role"] == "user" else "#e8c547"
#             st.markdown(f"""
#             <div style='margin-bottom: 1rem; padding: 1rem; background: {"#1e1e2e" if msg["role"] == "user" else "#1a1a26"};
#                  border-radius: 10px; border-left: 3px solid {role_color};'>
#                 <div style='font-family: IBM Plex Mono, monospace; font-size: 0.65rem; color: {role_color};
#                      letter-spacing: 1px; margin-bottom: 0.5rem;'>{role_icon} {"YOU" if msg["role"] == "user" else "RESEARCH AI"}</div>
#                 <div style='font-size: 0.9rem; line-height: 1.7;'>{msg["content"]}</div>
#             </div>
#             """, unsafe_allow_html=True)
# 
#         # Question input
#         question = st.text_input(
#             "Your question",
#             placeholder="e.g. What dataset was used? What are the limitations?",
#             label_visibility="collapsed",
#             key="qa_input"
#         )
# 
#         col1, col2 = st.columns([1, 4])
#         with col1:
#             ask_btn = st.button("Ask →", key="btn_ask")
#         with col2:
#             if st.button("Clear Chat", key="btn_clear"):
#                 st.session_state.messages = []
#                 st.rerun()
# 
#         if ask_btn and question:
#             if not api_key:
#                 st.error("API key required.")
#             else:
#                 st.session_state.messages.append({"role": "user", "content": question})
#                 client = openai.OpenAI(api_key=api_key)
#                 with st.spinner("Thinking..."):
#                     answer = ask_ai(
#                         client,
#                         f"Based on this research paper, answer the following question accurately and concisely.\n\nQuestion: {question}\n\nPaper text:\n{full_text[:4000]}",
#                         "You are an expert research assistant. Answer questions based strictly on the paper content."
#                     )
#                 st.session_state.messages.append({"role": "assistant", "content": answer})
#                 st.rerun()
# 
#     # ── Tab 4: Methodology ───────────────────────────────────────────────────
#     with tab4:
#         st.markdown("<br>", unsafe_allow_html=True)
#         if st.button("Analyze Methodology", key="btn_method"):
#             if not api_key:
#                 st.error("API key required.")
#             else:
#                 client = openai.OpenAI(api_key=api_key)
#                 with st.spinner("Analyzing methodology..."):
#                     method = ask_ai(
#                         client,
#                         f"Analyze the research methodology of this paper. Cover: research design, data collection, analysis techniques, tools/frameworks used, experimental setup, evaluation metrics, and any limitations of the methodology.\n\nPaper:\n{full_text[:4000]}",
#                         "You are a research methodology expert."
#                     )
#                 st.markdown(f"""
#                 <div class='card'>
#                     <div class='card-title'>🔬 &nbsp;Methodology Analysis</div>
#                     <div class='card-body'>{method}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#         st.markdown("<br>", unsafe_allow_html=True)
#         if st.button("Identify Research Gaps", key="btn_gaps"):
#             if not api_key:
#                 st.error("API key required.")
#             else:
#                 client = openai.OpenAI(api_key=api_key)
#                 with st.spinner("Identifying gaps..."):
#                     gaps = ask_ai(
#                         client,
#                         f"Based on this paper, identify: 1) research gaps the authors acknowledge, 2) potential future research directions, 3) limitations not fully addressed.\n\nPaper:\n{full_text[:4000]}",
#                         "You are a critical academic reviewer."
#                     )
#                 st.markdown(f"""
#                 <div class='card'>
#                     <div class='card-title'>🔭 &nbsp;Research Gaps & Future Work</div>
#                     <div class='card-body'>{gaps}</div>
#                 </div>
#                 """, unsafe_allow_html=True)
# 
#     # ── Tab 5: Raw Text ──────────────────────────────────────────────────────
#     with tab5:
#         st.markdown("<br>", unsafe_allow_html=True)
#         st.markdown("""
#         <div class='card-title'>📄 &nbsp;Extracted Text</div>
#         """, unsafe_allow_html=True)
#         st.text_area(
#             "Full extracted text",
#             value=full_text,
#             height=500,
#             label_visibility="collapsed"
#         )
# 
# else:
#     # Empty state
#     st.markdown("""
#     <div style='text-align: center; padding: 4rem 2rem;'>
#         <div style='font-size: 4rem; margin-bottom: 1rem;'>📑</div>
#         <div style='font-family: Playfair Display, serif; font-size: 1.5rem; color: #e8e8f0; margin-bottom: 0.5rem;'>
#             Upload a research paper to begin
#         </div>
#         <div style='font-family: IBM Plex Mono, monospace; font-size: 0.75rem; color: #7a7a9a; letter-spacing: 1px;'>
#             Supports PDF format · Powered by GPT-3.5
#         </div>
#     </div>
#     <div style='display: flex; justify-content: center; gap: 2rem; margin-top: 2rem; flex-wrap: wrap;'>
#         <div style='text-align: center; padding: 1.5rem; background: #12121a; border: 1px solid #2a2a3d; border-radius: 12px; width: 160px;'>
#             <div style='font-size: 2rem;'>🔬</div>
#             <div style='font-family: IBM Plex Mono, monospace; font-size: 0.7rem; color: #7a7a9a; margin-top: 0.5rem; letter-spacing: 1px;'>SUMMARIZE</div>
#         </div>
#         <div style='text-align: center; padding: 1.5rem; background: #12121a; border: 1px solid #2a2a3d; border-radius: 12px; width: 160px;'>
#             <div style='font-size: 2rem;'>💡</div>
#             <div style='font-family: IBM Plex Mono, monospace; font-size: 0.7rem; color: #7a7a9a; margin-top: 0.5rem; letter-spacing: 1px;'>INSIGHTS</div>
#         </div>
#         <div style='text-align: center; padding: 1.5rem; background: #12121a; border: 1px solid #2a2a3d; border-radius: 12px; width: 160px;'>
#             <div style='font-size: 2rem;'>❓</div>
#             <div style='font-family: IBM Plex Mono, monospace; font-size: 0.7rem; color: #7a7a9a; margin-top: 0.5rem; letter-spacing: 1px;'>Q&A CHAT</div>
#         </div>
#         <div style='text-align: center; padding: 1.5rem; background: #12121a; border: 1px solid #2a2a3d; border-radius: 12px; width: 160px;'>
#             <div style='font-size: 2rem;'>📊</div>
#             <div style='font-family: IBM Plex Mono, monospace; font-size: 0.7rem; color: #7a7a9a; margin-top: 0.5rem; letter-spacing: 1px;'>METHODOLOGY</div>
#         </div>
#     </div>
#     """, unsafe_allow_html=True)

!pip install streamlit pdfplumber openai pyngrok -q

# import subprocess
# subprocess.run(["pkill", "-f", "streamlit"], capture_output=True)
# subprocess.run(["pkill", "-f", "ngrok"], capture_output=True)
# import time
# time.sleep(3)
# print("✅ Cleared all processes")

# from pyngrok import ngrok
# import subprocess
# import time

# ngrok.set_auth_token("3Ajtb2xgc9p1aGsY31Gf3yhbjgi_7QakLtYz6nzRALdfyWxL8")  # your real token

# subprocess.Popen([
#     "streamlit", "run", "app.py",
#     "--server.port=8501",
#     "--server.headless=true"
# ])

# time.sleep(4)  # wait for streamlit to start

# public_url = ngrok.connect(8501)
# print("🚀 Open your app:", public_url)


# from pyngrok import ngrok
# import subprocess
# import time

# ngrok.set_auth_token("3Ajtb2xgc9p1aGsY31Gf3yhbjgi_7QakLtYz6nzRALdfyWxL8")

# process = subprocess.Popen([
#     "streamlit", "run", "app.py",
#     "--server.port=8501",
#     "--server.headless=true"
# ])

# print("⏳ Waiting for Streamlit to start...")
# time.sleep(10)  # increased to 10 seconds

# public_url = ngrok.connect(8502)
# print("🚀 Open your app:", public_url)

# import time
# while True:
#     time.sleep(60)



# import urllib.request
# try:
#     urllib.request.urlopen("http://localhost:8501")
#     print("✅ Streamlit is running!")
# except Exception as e:
#     print("❌ Streamlit not running yet:", e)

# import subprocess
# result = subprocess.run(["streamlit", "run", "app.py", "--server.port=8501"],
#                         capture_output=True, text=True, timeout=10)
# print(result.stdout)
# print(result.stderr)