# -*- coding: utf-8 -*-
"""Front_End

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSA7S0O_5SJIeoAhZLaE3oS5iE6Wn9Yp
"""

!pip install pdfplumber
!pip install transformers
!pip install nltk

!pip install streamlit pyngrok

!pip install streamlit pdfplumber groq pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile app.py
# import streamlit as st
# import pdfplumber
# from groq import Groq
# import time
# import io
# 
# # ─── CONFIG ──────────────────────────────────────────────────────────────────
# GROQ_API_KEY = # ← paste your Groq key here
# 
# client = Groq(api_key=GROQ_API_KEY)
# 
# 
# st.set_page_config(
#     page_title="Lumina Research AI",
#     page_icon="✦",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# st.markdown("""
# <style>
# @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:wght@300;400;500;600&family=Fira+Code:wght@400;500&display=swap');
# 
# /* ════════════════════════════════
#    CSS VARIABLES
# ════════════════════════════════ */
# :root {
#     --bg:      #060d06;
#     --surface: #0f1f0f;
#     --card:    #122012;
#     --border:  #1c3a1c;
#     --border2: #2d5e2d;
#     --g1:      #22c55e;
#     --g2:      #4ade80;
#     --g3:      #86efac;
#     --teal:    #2dd4bf;
#     --blue:    #60a5fa;
#     --text:    #e8f5e8;
#     --text2:   #9ec49e;
#     --text3:   #4a7a4a;
#     --white:   #f0faf0;
# }
# 
# /* ════════════════════════════════
#    BASE RESET
# ════════════════════════════════ */
# html, body, [class*="css"] {
#     font-family: 'DM Sans', sans-serif !important;
#     background-color: var(--bg) !important;
#     color: var(--text) !important;
# }
# #MainMenu, footer, header { visibility: hidden; }
# .block-container { padding: 0 2rem 3rem !important; max-width: 1400px !important; }
# 
# /* ════════════════════════════════
#    ★ STARS — pure CSS, always visible
#    No canvas, no JS needed!
# ════════════════════════════════ */
# @keyframes twinkle1 {
#     0%,100%{opacity:0.2} 50%{opacity:1}
# }
# @keyframes twinkle2 {
#     0%,100%{opacity:0.8} 50%{opacity:0.1}
# }
# @keyframes twinkle3 {
#     0%,100%{opacity:0.5} 33%{opacity:1} 66%{opacity:0.2}
# }
# @keyframes shootingStar {
#     0%   { transform: translateX(0) translateY(0); opacity:1; width:3px; }
#     100% { transform: translateX(600px) translateY(300px); opacity:0; width:120px; }
# }
# @keyframes drift {
#     0%  { transform: translateY(0px); }
#     50% { transform: translateY(-8px); }
#     100%{ transform: translateY(0px); }
# }
# @keyframes nebulaFloat {
#     0%,100% { transform: scale(1) translateX(0); opacity:0.6; }
#     50%      { transform: scale(1.05) translateX(20px); opacity:0.9; }
# }
# 
# /* The star layer sits behind EVERYTHING */
# body::before {
#     content: '';
#     position: fixed;
#     top:0; left:0; right:0; bottom:0;
#     z-index: 0;
#     pointer-events: none;
#     /* dozens of radial gradients = stars */
#     background:
#         /* big glow nebulas */
#         radial-gradient(ellipse 600px 400px at 20% 30%, rgba(34,197,94,0.07) 0%, transparent 70%),
#         radial-gradient(ellipse 500px 350px at 80% 70%, rgba(45,212,191,0.05) 0%, transparent 70%),
#         radial-gradient(ellipse 400px 300px at 60% 10%, rgba(96,165,250,0.04) 0%, transparent 70%),
#         /* stars — white */
#         radial-gradient(circle 1.5px at 5% 10%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 12% 25%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 18% 5%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 25% 40%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 30% 15%, #86efac 0%, transparent 100%),
#         radial-gradient(circle 1px at 35% 55%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 42% 8%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 48% 35%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 55% 20%, #2dd4bf 0%, transparent 100%),
#         radial-gradient(circle 1px at 60% 50%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 65% 12%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 70% 60%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 75% 28%, #86efac 0%, transparent 100%),
#         radial-gradient(circle 1px at 80% 45%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 85% 18%, #4ade80 0%, transparent 100%),
#         radial-gradient(circle 1px at 90% 38%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 95% 8%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 8% 65%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 15% 75%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 22% 85%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 28% 70%, #86efac 0%, transparent 100%),
#         radial-gradient(circle 1px at 38% 80%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 45% 90%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 52% 68%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 58% 78%, #2dd4bf 0%, transparent 100%),
#         radial-gradient(circle 1px at 64% 88%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 72% 72%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 78% 82%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 84% 65%, #86efac 0%, transparent 100%),
#         radial-gradient(circle 1px at 92% 78%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 3% 45%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 10% 52%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 47% 3%, #4ade80 0%, transparent 100%),
#         radial-gradient(circle 1px at 33% 93%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 88% 5%, #d4ffe4 0%, transparent 100%),
#         radial-gradient(circle 1px at 97% 55%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 1.5px at 50% 97%, #86efac 0%, transparent 100%),
#         radial-gradient(circle 1px at 20% 97%, #ffffff 0%, transparent 100%),
#         radial-gradient(circle 2px at 74% 96%, #d4ffe4 0%, transparent 100%),
#         /* base dark bg */
#         #060d06;
#     animation: nebulaFloat 20s ease-in-out infinite;
# }
# 
# /* shooting stars via pseudo elements on specific divs */
# .shoot1, .shoot2, .shoot3 {
#     position: fixed;
#     height: 1.5px;
#     background: linear-gradient(90deg, rgba(255,255,255,0), #4ade80, rgba(255,255,255,0));
#     border-radius: 999px;
#     z-index: 0;
#     pointer-events: none;
#     animation: shootingStar linear infinite;
# }
# .shoot1 { top: 15%; left: -5%; width: 3px; animation-duration: 4s; animation-delay: 0s; }
# .shoot2 { top: 35%; left: -5%; width: 3px; animation-duration: 6s; animation-delay: 2s; }
# .shoot3 { top: 60%; left: -5%; width: 3px; animation-duration: 5s; animation-delay: 4s; }
# 
# /* All Streamlit content must be above the star layer */
# section[data-testid="stMain"],
# section[data-testid="stSidebar"],
# .block-container,
# .stTabs,
# [data-testid="stFileUploader"] {
#     position: relative;
#     z-index: 1;
# }
# 
# /* ════════════════════════════════
#    SIDEBAR — BRIGHT GREEN VISIBLE
# ════════════════════════════════ */
# section[data-testid="stSidebar"] {
#     background: #071407 !important;
#     border-right: 3px solid #22c55e !important;
#     box-shadow: 8px 0 60px rgba(34,197,94,0.3) !important;
#     min-width: 285px !important;
#     z-index: 100 !important;
# }
# section[data-testid="stSidebar"] * { color: var(--text) !important; }
# 
# /* ★ THE SIDEBAR TOGGLE BUTTON — make it HUGE and GREEN ★ */
# [data-testid="collapsedControl"] {
#     background: #22c55e !important;
#     width: 32px !important;
#     height: 72px !important;
#     border-radius: 0 12px 12px 0 !important;
#     display: flex !important;
#     align-items: center !important;
#     justify-content: center !important;
#     box-shadow: 4px 0 24px rgba(34,197,94,0.6) !important;
#     z-index: 999 !important;
#     top: 50% !important;
#     border: none !important;
# }
# [data-testid="collapsedControl"]:hover {
#     background: #4ade80 !important;
#     box-shadow: 4px 0 36px rgba(74,222,128,0.8) !important;
# }
# [data-testid="collapsedControl"] svg,
# [data-testid="collapsedControl"] svg * {
#     fill: #060d06 !important;
#     stroke: #060d06 !important;
#     color: #060d06 !important;
# }
# /* Also style the expand button inside the sidebar */
# button[data-testid="baseButton-header"] {
#     background: rgba(34,197,94,0.2) !important;
#     border: 1px solid rgba(34,197,94,0.5) !important;
#     border-radius: 8px !important;
#     color: #4ade80 !important;
# }
# 
# /* ════════════════════════════════
#    ANIMATIONS
# ════════════════════════════════ */
# @keyframes fadeSlideUp {
#     from { opacity:0; transform:translateY(24px); }
#     to   { opacity:1; transform:translateY(0); }
# }
# @keyframes pulseGlow {
#     0%,100% { box-shadow:0 0 10px rgba(34,197,94,0.3); }
#     50%      { box-shadow:0 0 30px rgba(34,197,94,0.7),0 0 60px rgba(34,197,94,0.2); }
# }
# @keyframes gradShift {
#     0%   { background-position:0% 50%; }
#     50%  { background-position:100% 50%; }
#     100% { background-position:0% 50%; }
# }
# @keyframes blinkDot {
#     0%,100%{opacity:1} 50%{opacity:0.2}
# }
# @keyframes ripple {
#     0%   {transform:scale(1);opacity:0.7}
#     100% {transform:scale(2.8);opacity:0}
# }
# @keyframes slideLeft {
#     from{opacity:0;transform:translateX(-16px)}
#     to{opacity:1;transform:translateX(0)}
# }
# @keyframes floatIcon {
#     0%,100%{transform:translateY(0)} 50%{transform:translateY(-8px)}
# }
# @keyframes borderSpin {
#     0%  {border-color:var(--g1)}
#     33% {border-color:var(--teal)}
#     66% {border-color:var(--blue)}
#     100%{border-color:var(--g1)}
# }
# 
# /* ════════════════════════════════
#    HERO
# ════════════════════════════════ */
# .hero-wrap {
#     position:relative; text-align:center;
#     padding:5.5rem 2rem 4rem;
#     margin:0 -2rem 3rem;
#     overflow:hidden;
#     border-bottom:1px solid var(--border2);
#     animation:fadeSlideUp 0.8s ease both;
# }
# .hero-wrap::before {
#     content:''; position:absolute; inset:0;
#     background:
#         radial-gradient(ellipse 80% 55% at 50% -5%, rgba(34,197,94,0.22) 0%, transparent 65%),
#         radial-gradient(ellipse 35% 50% at 10% 100%, rgba(45,212,191,0.1) 0%, transparent 55%),
#         radial-gradient(ellipse 35% 50% at 90% 100%, rgba(96,165,250,0.07) 0%, transparent 55%);
#     pointer-events:none;
# }
# .hero-wrap::after {
#     content:''; position:absolute; inset:0;
#     background-image:radial-gradient(circle, rgba(34,197,94,0.2) 1px, transparent 1px);
#     background-size:38px 38px;
#     mask-image:radial-gradient(ellipse 80% 70% at 50% 0%, black 20%, transparent 80%);
#     pointer-events:none;
# }
# .hero-inner{position:relative;z-index:2;}
# .hero-badge {
#     display:inline-flex; align-items:center; gap:0.6rem;
#     padding:0.4rem 1.3rem;
#     background:rgba(34,197,94,0.13);
#     border:1px solid rgba(34,197,94,0.45);
#     border-radius:999px;
#     font-family:'Fira Code',monospace;
#     font-size:0.68rem; color:var(--g2);
#     letter-spacing:2px; text-transform:uppercase;
#     margin-bottom:1.8rem;
#     animation:pulseGlow 3s ease-in-out infinite, fadeSlideUp 0.7s ease both;
# }
# .bdot {
#     width:7px;height:7px;
#     background:var(--g1);border-radius:50%;
#     animation:blinkDot 1.5s ease-in-out infinite;
#     position:relative; flex-shrink:0;
# }
# .bdot::after {
#     content:'';position:absolute;inset:-3px;
#     border-radius:50%;border:1px solid var(--g1);
#     animation:ripple 1.5s ease-in-out infinite;
# }
# .hero-title {
#     font-family:'DM Serif Display',serif;
#     font-size:5rem; font-weight:400; color:var(--white);
#     line-height:1.05; margin:0 0 1.1rem; letter-spacing:-2px;
#     animation:fadeSlideUp 0.8s ease 0.15s both;
# }
# .grad-text {
#     font-style:italic;
#     background:linear-gradient(135deg,#4ade80,#2dd4bf,#60a5fa,#4ade80);
#     background-size:300% auto;
#     -webkit-background-clip:text;
#     -webkit-text-fill-color:transparent;
#     background-clip:text;
#     animation:gradShift 4s linear infinite;
# }
# .hero-desc {
#     font-size:1.15rem; color:var(--text2);
#     font-weight:300; max-width:580px;
#     margin:0 auto 2.8rem; line-height:1.75;
#     animation:fadeSlideUp 0.8s ease 0.3s both;
# }
# .hero-stats {
#     display:flex; justify-content:center; gap:3.5rem;
#     animation:fadeSlideUp 0.8s ease 0.45s both;
# }
# .stat-num {
#     font-family:'DM Serif Display',serif; font-size:2.4rem;
#     background:linear-gradient(135deg,var(--g2),var(--teal));
#     -webkit-background-clip:text; -webkit-text-fill-color:transparent;
#     background-clip:text; line-height:1;
# }
# .stat-lbl {
#     font-size:0.68rem; color:var(--text3);
#     text-transform:uppercase; letter-spacing:1.5px;
#     margin-top:0.3rem; font-family:'Fira Code',monospace;
# }
# 
# /* ════════════════════════════════
#    SECTION LABEL
# ════════════════════════════════ */
# .slabel {
#     font-family:'Fira Code',monospace;
#     font-size:0.65rem; color:var(--g2);
#     letter-spacing:3px; text-transform:uppercase;
#     margin-bottom:1rem;
#     display:flex; align-items:center; gap:0.75rem;
#     animation:fadeSlideUp 0.5s ease both;
# }
# .slabel::after {
#     content:''; flex:1; height:1px;
#     background:linear-gradient(90deg,var(--border2),transparent);
# }
# 
# /* ════════════════════════════════
#    CARDS
# ════════════════════════════════ */
# .lcard {
#     background:rgba(18,32,18,0.9);
#     backdrop-filter:blur(12px);
#     border:1px solid var(--border2);
#     border-radius:16px; padding:2rem;
#     margin-bottom:1.5rem; position:relative; overflow:hidden;
#     animation:fadeSlideUp 0.5s ease both;
#     transition:border-color 0.3s, box-shadow 0.3s, transform 0.3s;
# }
# .lcard:hover {
#     border-color:rgba(34,197,94,0.5);
#     box-shadow:0 12px 50px rgba(34,197,94,0.1);
#     transform:translateY(-2px);
# }
# .lcard::before {
#     content:''; position:absolute; top:0;left:0;right:0; height:2px;
#     background:linear-gradient(90deg,transparent,var(--g1) 30%,var(--teal) 70%,transparent);
#     opacity:0.55;
# }
# .lcard-accent{border-color:rgba(34,197,94,0.3);}
# .card-text{font-size:1rem;line-height:1.9;color:var(--text2);font-weight:300;}
# 
# /* ════════════════════════════════
#    PILLS
# ════════════════════════════════ */
# .pill-row{display:flex;gap:0.75rem;flex-wrap:wrap;margin-bottom:2rem;animation:fadeSlideUp 0.5s ease 0.2s both;}
# .pill {
#     display:flex;align-items:center;gap:0.5rem;
#     background:rgba(15,31,15,0.9);
#     border:1px solid var(--border2); border-radius:10px;
#     padding:0.55rem 1rem; font-size:0.85rem; color:var(--text2);
#     transition:all 0.25s; animation:borderSpin 6s linear infinite;
# }
# .pill:hover{transform:translateY(-3px);box-shadow:0 6px 20px rgba(34,197,94,0.15);}
# .pv{color:var(--g2);font-weight:600;font-family:'Fira Code',monospace;}
# 
# /* ════════════════════════════════
#    ALERT
# ════════════════════════════════ */
# .alert-ok {
#     background:rgba(34,197,94,0.1);
#     border:1px solid rgba(34,197,94,0.4); border-left:4px solid var(--g1);
#     border-radius:12px; padding:1rem 1.4rem;
#     color:var(--g3); font-size:0.95rem;
#     margin-bottom:1.5rem;
#     display:flex; align-items:center; gap:0.75rem;
#     animation:fadeSlideUp 0.4s ease both;
# }
# 
# /* ════════════════════════════════
#    FEATURE GRID
# ════════════════════════════════ */
# .feat-grid {
#     display:grid;grid-template-columns:repeat(4,1fr);
#     gap:1rem;margin:2.5rem 0;
#     animation:fadeSlideUp 0.8s ease 0.5s both;
# }
# .feat-card {
#     background:rgba(15,31,15,0.85);
#     backdrop-filter:blur(8px);
#     border:1px solid var(--border2);
#     border-radius:14px;padding:1.8rem 1.2rem;
#     text-align:center;transition:all 0.3s;
#     position:relative;overflow:hidden;
# }
# .feat-card::after {
#     content:'';position:absolute;
#     bottom:0;left:0;right:0;height:2px;
#     background:linear-gradient(90deg,var(--g1),var(--teal));
#     opacity:0;transition:opacity 0.3s;
# }
# .feat-card:hover{border-color:rgba(34,197,94,0.5);transform:translateY(-6px);box-shadow:0 16px 50px rgba(34,197,94,0.15);}
# .feat-card:hover::after{opacity:1;}
# .fi{font-size:1.6rem;margin-bottom:0.75rem;animation:floatIcon 3s ease-in-out infinite;}
# .feat-card:nth-child(2) .fi{animation-delay:0.4s;}
# .feat-card:nth-child(3) .fi{animation-delay:0.8s;}
# .feat-card:nth-child(4) .fi{animation-delay:1.2s;}
# .feat-card:nth-child(5) .fi{animation-delay:0.2s;}
# .feat-card:nth-child(6) .fi{animation-delay:0.6s;}
# .feat-card:nth-child(7) .fi{animation-delay:1.0s;}
# .feat-card:nth-child(8) .fi{animation-delay:1.4s;}
# .ft{font-size:0.95rem;font-weight:600;color:var(--white);margin-bottom:0.4rem;}
# .fd{font-size:0.8rem;color:var(--text3);line-height:1.5;}
# 
# /* ════════════════════════════════
#    BUTTONS
# ════════════════════════════════ */
# .stButton > button {
#     background:rgba(34,197,94,0.12) !important;
#     color:var(--g2) !important;
#     font-family:'DM Sans',sans-serif !important;
#     font-weight:600 !important; font-size:0.9rem !important;
#     border:1.5px solid rgba(34,197,94,0.45) !important;
#     border-radius:10px !important; padding:0.65rem 1.5rem !important;
#     transition:all 0.25s !important; letter-spacing:0.3px !important;
# }
# .stButton > button:hover {
#     background:rgba(34,197,94,0.22) !important;
#     border-color:var(--g1) !important;
#     transform:translateY(-2px) !important;
#     box-shadow:0 6px 24px rgba(34,197,94,0.3) !important;
#     color:#ffffff !important;
# }
# .stDownloadButton > button {
#     background:linear-gradient(135deg,#22c55e,#2dd4bf) !important;
#     color:#040a04 !important; font-weight:700 !important;
#     font-family:'DM Sans',sans-serif !important;
#     font-size:0.88rem !important; border:none !important;
#     border-radius:10px !important; padding:0.65rem 1.5rem !important;
#     transition:all 0.25s !important;
#     box-shadow:0 4px 18px rgba(34,197,94,0.35) !important;
# }
# .stDownloadButton > button:hover {
#     transform:translateY(-3px) !important;
#     box-shadow:0 10px 30px rgba(34,197,94,0.5) !important;
# }
# 
# /* ════════════════════════════════
#    INPUTS
# ════════════════════════════════ */
# .stTextInput>div>div>input,
# .stTextArea>div>div>textarea {
#     background:rgba(15,31,15,0.9) !important;
#     border:1.5px solid var(--border2) !important;
#     border-radius:10px !important; color:var(--white) !important;
#     font-family:'DM Sans',sans-serif !important;
#     font-size:1rem !important; padding:0.75rem 1rem !important;
#     transition:all 0.2s !important;
# }
# .stTextInput>div>div>input:focus,
# .stTextArea>div>div>textarea:focus {
#     border-color:var(--g1) !important;
#     box-shadow:0 0 0 3px rgba(34,197,94,0.18) !important;
# }
# .stTextInput>div>div>input::placeholder,
# .stTextArea>div>div>textarea::placeholder{color:var(--text3) !important;}
# 
# /* ════════════════════════════════
#    TABS
# ════════════════════════════════ */
# .stTabs [data-baseweb="tab-list"] {
#     background:rgba(15,31,15,0.95) !important;
#     border-radius:12px !important; padding:5px !important;
#     gap:3px !important; border:1px solid var(--border2) !important;
# }
# .stTabs [data-baseweb="tab"] {
#     background:transparent !important; color:var(--text3) !important;
#     font-family:'DM Sans',sans-serif !important;
#     font-size:0.88rem !important; font-weight:500 !important;
#     border-radius:9px !important; padding:0.5rem 1.3rem !important;
#     transition:all 0.2s !important;
# }
# .stTabs [data-baseweb="tab"]:hover{color:var(--g2) !important;background:rgba(34,197,94,0.07) !important;}
# .stTabs [aria-selected="true"] {
#     background:rgba(34,197,94,0.15) !important;
#     color:var(--g2) !important;
#     border:1px solid rgba(34,197,94,0.4) !important;
# }
# 
# /* ════════════════════════════════
#    CHAT
# ════════════════════════════════ */
# .cu{background:rgba(34,197,94,0.08);border:1px solid rgba(34,197,94,0.22);border-radius:16px 16px 4px 16px;padding:1rem 1.3rem;margin-bottom:1rem;animation:slideLeft 0.35s ease both;}
# .ca{background:rgba(15,31,15,0.9);border:1px solid var(--border2);border-radius:16px 16px 16px 4px;padding:1rem 1.3rem;margin-bottom:1rem;animation:slideLeft 0.35s ease both;}
# .cr{font-family:'Fira Code',monospace;font-size:0.63rem;letter-spacing:2px;text-transform:uppercase;margin-bottom:0.5rem;font-weight:500;}
# .cc{font-size:0.95rem;line-height:1.75;color:var(--text2);}
# 
# /* ════════════════════════════════
#    FILE UPLOADER
# ════════════════════════════════ */
# [data-testid="stFileUploader"]>div {
#     background:rgba(15,31,15,0.85) !important;
#     border:2px dashed var(--border2) !important;
#     border-radius:16px !important; padding:2.5rem !important;
#     transition:all 0.3s !important;
# }
# [data-testid="stFileUploader"]>div:hover {
#     border-color:var(--g1) !important;
#     box-shadow:0 0 40px rgba(34,197,94,0.1) !important;
# }
# 
# /* ════════════════════════════════
#    MISC
# ════════════════════════════════ */
# .stSpinner>div{border-top-color:var(--g1) !important;}
# ::-webkit-scrollbar{width:5px;}
# ::-webkit-scrollbar-track{background:var(--bg);}
# ::-webkit-scrollbar-thumb{background:var(--border2);border-radius:99px;}
# ::-webkit-scrollbar-thumb:hover{background:var(--g1);}
# 
# /* ════════════════════════════════
#    SIDEBAR INTERIOR
# ════════════════════════════════ */
# .sb-logo{font-family:'DM Serif Display',serif;font-size:2rem;color:var(--white);font-weight:400;letter-spacing:-0.5px;line-height:1;}
# .sb-tag{font-family:'Fira Code',monospace;font-size:0.58rem;color:var(--text3);letter-spacing:2px;text-transform:uppercase;margin-top:0.2rem;}
# .sb-live{display:flex;align-items:center;gap:0.5rem;background:rgba(34,197,94,0.1);border:1px solid rgba(34,197,94,0.3);border-radius:8px;padding:0.5rem 0.85rem;margin:0.85rem 0;font-family:'Fira Code',monospace;font-size:0.63rem;color:var(--g2);}
# .ld{width:7px;height:7px;background:var(--g1);border-radius:50%;animation:blinkDot 1.2s ease-in-out infinite;position:relative;flex-shrink:0;}
# .ld::after{content:'';position:absolute;inset:-3px;border-radius:50%;border:1px solid var(--g1);animation:ripple 1.5s ease-in-out infinite;}
# .sb-st{font-family:'Fira Code',monospace;font-size:0.58rem;color:var(--g1);letter-spacing:3px;text-transform:uppercase;margin:1.1rem 0 0.65rem;display:flex;align-items:center;gap:0.5rem;}
# .sb-st::after{content:'';flex:1;height:1px;background:linear-gradient(90deg,var(--border2),transparent);}
# .sb-step{display:flex;align-items:flex-start;gap:0.7rem;margin-bottom:0.85rem;font-size:0.88rem;color:var(--text2);line-height:1.4;animation:slideLeft 0.4s ease both;}
# .sn{flex-shrink:0;width:23px;height:23px;background:rgba(34,197,94,0.15);border:1px solid rgba(34,197,94,0.4);border-radius:50%;display:flex;align-items:center;justify-content:center;font-family:'Fira Code',monospace;font-size:0.62rem;color:var(--g2);font-weight:600;margin-top:1px;}
# .sb-mod{display:flex;align-items:center;gap:0.65rem;padding:0.58rem 0.85rem;background:rgba(34,197,94,0.06);border:1px solid rgba(34,197,94,0.14);border-radius:9px;margin-bottom:0.45rem;font-size:0.85rem;color:var(--text2);transition:all 0.22s;animation:slideLeft 0.4s ease both;}
# .sb-mod:hover{background:rgba(34,197,94,0.14);border-color:rgba(34,197,94,0.45);color:var(--white);transform:translateX(6px);box-shadow:0 4px 16px rgba(34,197,94,0.15);}
# .sd{width:7px;height:7px;background:linear-gradient(135deg,var(--g1),var(--teal));border-radius:50%;flex-shrink:0;animation:blinkDot 2s ease-in-out infinite;}
# .sb-ft{font-family:'Fira Code',monospace;font-size:0.58rem;color:var(--text3);line-height:2;margin-top:1rem;border-top:1px solid var(--border);padding-top:0.85rem;}
# </style>
# 
# <!-- Shooting stars (CSS-only divs) -->
# <div class="shoot1"></div>
# <div class="shoot2"></div>
# <div class="shoot3"></div>
# """, unsafe_allow_html=True)
# 
# 
# # ─── Helpers ─────────────────────────────────────────────────────────────────
# def extract_text(f):
#     txt=""
#     with pdfplumber.open(f) as pdf:
#         for p in pdf.pages:
#             t=p.extract_text()
#             if t: txt+=t+"\n"
#     return txt
# 
# def ask_groq(prompt, sys="You are an expert AI research assistant."):
#     r=client.chat.completions.create(
#         model="llama-3.3-70b-versatile",
#         messages=[{"role":"system","content":sys},{"role":"user","content":prompt}],
#         max_tokens=1500, temperature=0.4)
#     return r.choices[0].message.content
# 
# def make_report(filename,summary="",insights="",methodology="",citations="",qa=[]):
#     L=["╔"+"═"*64+"╗","║"+"   LUMINA RESEARCH AI — FULL ANALYSIS REPORT".center(64)+"║","╚"+"═"*64+"╝",
#        f"  Paper   : {filename}","  Powered : Groq · LLaMA 3.3 70B","━"*66,""]
#     if summary:    L+=["  ✦  EXECUTIVE SUMMARY","  "+"─"*50,summary,""]
#     if insights:   L+=["  ◈  KEY INSIGHTS","  "+"─"*50,insights,""]
#     if methodology:L+=["  ◉  METHODOLOGY","  "+"─"*50,methodology,""]
#     if citations:  L+=["  ◇  CITATIONS","  "+"─"*50,citations,""]
#     if qa:
#         L+=["  ◎  Q&A","  "+"─"*50]
#         for m in qa: L.append(f"  {'[You]' if m['role']=='user' else '[AI] '}  {m['content']}")
#     L+=["","━"*66,"  Lumina Research AI","━"*66]
#     return "\n".join(L)
# 
# 
# # ─── SIDEBAR ─────────────────────────────────────────────────────────────────
# with st.sidebar:
#     st.markdown("""
#     <div style='padding:1.5rem 1.5rem 0;'>
#         <div class='sb-logo'>Lumina<span class='grad-text'>AI</span></div>
#         <div class='sb-tag'>Research Intelligence · v3.0</div>
#         <div class='sb-live'><div class='ld'></div>System Online &nbsp;·&nbsp; Groq Connected</div>
#         <div class='sb-st'>How It Works</div>
#         <div class='sb-step'><div class='sn'>1</div><div>Upload any research PDF below</div></div>
#         <div class='sb-step'><div class='sn'>2</div><div>AI auto-generates full summary</div></div>
#         <div class='sb-step'><div class='sn'>3</div><div>Explore all tabs — insights, Q&A, methodology</div></div>
#         <div class='sb-step'><div class='sn'>4</div><div>Download your complete report</div></div>
#         <div class='sb-st'>Capabilities</div>
#         <div class='sb-mod'><div class='sd'></div>Auto Summary Generation</div>
#         <div class='sb-mod'><div class='sd'></div>Key Insight Extraction</div>
#         <div class='sb-mod'><div class='sd'></div>Interactive Q&A Chat</div>
#         <div class='sb-mod'><div class='sd'></div>Methodology Deep Dive</div>
#         <div class='sb-mod'><div class='sd'></div>Research Gap Detection</div>
#         <div class='sb-mod'><div class='sd'></div>5-Format Citation Builder</div>
#         <div class='sb-mod'><div class='sd'></div>Full Report Download</div>
#         <div class='sb-ft'>Model &nbsp;&nbsp;: LLaMA 3.3 70B<br>Provider : Groq Cloud<br>Cost &nbsp;&nbsp;&nbsp;: Free Forever ✦</div>
#     </div>""", unsafe_allow_html=True)
# 
# 
# # ─── HERO ─────────────────────────────────────────────────────────────────────
# st.markdown("""
# <div class='hero-wrap'>
#   <div class='hero-inner'>
#     <div class='hero-badge'><div class='bdot'></div>AI-Powered Academic Intelligence</div>
#     <div class='hero-title'>Understand Any Paper<br><span class='grad-text'>In Seconds.</span></div>
#     <div class='hero-desc'>Upload a research PDF and let Lumina AI decode it — summaries, insights, Q&A, methodology and citations, all in one beautiful place.</div>
#     <div class='hero-stats'>
#       <div><div class='stat-num'>7+</div><div class='stat-lbl'>Analysis Modules</div></div>
#       <div><div class='stat-num'>70B</div><div class='stat-lbl'>Parameter Model</div></div>
#       <div><div class='stat-num'>Free</div><div class='stat-lbl'>No Cost Ever</div></div>
#       <div><div class='stat-num'>&lt;10s</div><div class='stat-lbl'>Analysis Time</div></div>
#     </div>
#   </div>
# </div>""", unsafe_allow_html=True)
# 
# # ─── UPLOAD ──────────────────────────────────────────────────────────────────
# st.markdown("<div class='slabel'>✦ &nbsp;Upload Research Paper</div>", unsafe_allow_html=True)
# uploaded_file = st.file_uploader("", type=["pdf"], label_visibility="collapsed")
# 
# # ─── MAIN ────────────────────────────────────────────────────────────────────
# if uploaded_file:
#     with st.spinner("Extracting content..."):
#         full_text=extract_text(uploaded_file)
#         words=len(full_text.split()); chars=len(full_text)
#         pages=max(1,chars//2000); rtime=max(1,words//200)
# 
#     st.markdown(f"""
#     <div class='alert-ok'><span style='font-size:1.2rem;'>✦</span>
#     <div><strong style='color:var(--g2);'>Paper loaded!</strong> &nbsp;AI analysis ready — explore tabs below.</div></div>
#     <div class='pill-row'>
#         <div class='pill'>📝 Words <span class='pv'>{words:,}</span></div>
#         <div class='pill'>🔤 Chars <span class='pv'>{chars:,}</span></div>
#         <div class='pill'>📄 Pages <span class='pv'>~{pages}</span></div>
#         <div class='pill'>⏱ Read <span class='pv'>~{rtime} min</span></div>
#         <div class='pill'>📁 <span class='pv'>{uploaded_file.name}</span></div>
#     </div>""", unsafe_allow_html=True)
# 
#     t1,t2,t3,t4,t5,t6=st.tabs(["✦  Summary","◈  Insights","◎  Q&A Chat","◉  Methodology","◇  Citations","◌  Raw Text"])
# 
#     with t1:
#         st.markdown("<br>",unsafe_allow_html=True)
#         if "summary" not in st.session_state or st.session_state.get("lf")!=uploaded_file.name:
#             with st.spinner("Generating summary..."):
#                 st.session_state.summary=ask_groq(
#                     f"Write a rich structured summary with bold headers: **Title & Authors**, **Problem Statement**, **Objectives**, **Methodology**, **Key Results**, **Conclusions**, **Impact**.\n\nPaper:\n{full_text[:4500]}",
#                     "You are a world-class academic researcher.")
#                 st.session_state.lf=uploaded_file.name
#         st.markdown(f"<div class='lcard lcard-accent'><div class='slabel'>✦ &nbsp;Executive Summary</div><div class='card-text'>{st.session_state.summary}</div></div>",unsafe_allow_html=True)
#         c1,c2,_=st.columns([1,1.2,3])
#         with c1:
#             if st.button("↺  Regenerate"): del st.session_state["summary"]; st.rerun()
#         with c2:
#             if st.session_state.get("summary"):
#                 st.download_button("↓  Download",data=make_report(uploaded_file.name,summary=st.session_state.summary).encode(),file_name=f"summary_{uploaded_file.name.replace('.pdf','')}.txt",mime="text/plain")
# 
#     with t2:
#         st.markdown("<br>",unsafe_allow_html=True)
#         if st.button("◈  Extract Key Insights"):
#             with st.spinner("Extracting..."):
#                 st.session_state.insights=ask_groq(
#                     f"Extract 7 key insights. Each: bold **Title**, 3-4 sentence explanation, **Why It Matters**. Number 1-7.\n\nPaper:\n{full_text[:4500]}",
#                     "Expert at identifying transformative research insights.")
#         if st.session_state.get("insights"):
#             st.markdown(f"<div class='lcard lcard-accent'><div class='slabel'>◈ &nbsp;Key Intelligence</div><div class='card-text'>{st.session_state.insights}</div></div>",unsafe_allow_html=True)
#             st.download_button("↓  Download Insights",data=make_report(uploaded_file.name,insights=st.session_state.insights).encode(),file_name=f"insights_{uploaded_file.name.replace('.pdf','')}.txt",mime="text/plain")
# 
#     with t3:
#         st.markdown("<br>",unsafe_allow_html=True)
#         st.markdown("<div class='slabel'>◎ &nbsp;Interactive Q&A</div>",unsafe_allow_html=True)
#         if "messages" not in st.session_state: st.session_state.messages=[]
#         for m in st.session_state.messages:
#             if m["role"]=="user":
#                 st.markdown(f"<div class='cu'><div class='cr' style='color:var(--g2);'>You</div><div class='cc'>{m['content']}</div></div>",unsafe_allow_html=True)
#             else:
#                 st.markdown(f"<div class='ca'><div class='cr' style='color:var(--teal);'>Lumina AI</div><div class='cc'>{m['content']}</div></div>",unsafe_allow_html=True)
#         q=st.text_input("",placeholder="Ask anything about the paper...",label_visibility="collapsed",key="qi")
#         c1,c2,c3=st.columns([1,1,2])
#         with c1: ab=st.button("◎  Ask AI")
#         with c2:
#             if st.button("✕  Clear"): st.session_state.messages=[]; st.rerun()
#         with c3:
#             if st.session_state.messages:
#                 st.download_button("↓  Download Q&A",data=make_report(uploaded_file.name,qa=st.session_state.messages).encode(),file_name=f"qa_{uploaded_file.name.replace('.pdf','')}.txt",mime="text/plain")
#         if ab and q:
#             st.session_state.messages.append({"role":"user","content":q})
#             with st.spinner("Thinking..."):
#                 ans=ask_groq(f"Answer based on paper. Be detailed.\n\nQuestion: {q}\n\nPaper:\n{full_text[:4500]}","Elite research assistant.")
#             st.session_state.messages.append({"role":"assistant","content":ans})
#             st.rerun()
# 
#     with t4:
#         st.markdown("<br>",unsafe_allow_html=True)
#         c1,c2=st.columns(2)
#         with c1:
#             if st.button("◉  Analyze Methodology",key="bm"):
#                 with st.spinner("Analyzing..."):
#                     st.session_state.methodology=ask_groq(f"Deep methodology: **Research Design**, **Data Sources**, **Preprocessing**, **Architecture**, **Training**, **Evaluation**, **Baselines**, **Limitations**.\n\nPaper:\n{full_text[:4500]}","Research methodology expert.")
#         with c2:
#             if st.button("◎  Gap Analysis",key="bg"):
#                 with st.spinner("Finding gaps..."):
#                     st.session_state.gaps=ask_groq(f"Identify all gaps. Propose 3 concrete follow-up ideas.\n\nPaper:\n{full_text[:4500]}","Critical academic reviewer.")
#         if st.session_state.get("methodology"):
#             st.markdown(f"<div class='lcard lcard-accent'><div class='slabel'>◉ &nbsp;Methodology</div><div class='card-text'>{st.session_state.methodology}</div></div>",unsafe_allow_html=True)
#         if st.session_state.get("gaps"):
#             st.markdown(f"<div class='lcard'><div class='slabel'>◎ &nbsp;Research Gaps</div><div class='card-text'>{st.session_state.gaps}</div></div>",unsafe_allow_html=True)
#         if st.session_state.get("summary"):
#             st.markdown("<br>",unsafe_allow_html=True)
#             st.download_button("↓  Download Full Report",data=make_report(uploaded_file.name,summary=st.session_state.get("summary",""),insights=st.session_state.get("insights",""),methodology=st.session_state.get("methodology",""),qa=st.session_state.get("messages",[])).encode(),file_name=f"full_report_{uploaded_file.name.replace('.pdf','')}.txt",mime="text/plain")
# 
#     with t5:
#         st.markdown("<br>",unsafe_allow_html=True)
#         if st.button("◇  Generate All 5 Citation Formats"):
#             with st.spinner("Building citations..."):
#                 st.session_state.citations=ask_groq(f"Generate complete citations:\n**1. APA 7th**\n**2. MLA 9th**\n**3. Chicago 17th**\n**4. BibTeX**\n**5. IEEE**\n\nPaper:\n{full_text[:2500]}","Master citation expert.")
#         if st.session_state.get("citations"):
#             st.markdown(f"<div class='lcard lcard-accent'><div class='slabel'>◇ &nbsp;Citation Library</div><div class='card-text' style='font-family:Fira Code,monospace;font-size:0.88rem;line-height:2.2;'>{st.session_state.citations}</div></div>",unsafe_allow_html=True)
#             st.download_button("↓  Download Citations",data=make_report(uploaded_file.name,citations=st.session_state.citations).encode(),file_name=f"citations_{uploaded_file.name.replace('.pdf','')}.txt",mime="text/plain")
# 
#     with t6:
#         st.markdown("<br>",unsafe_allow_html=True)
#         st.markdown("<div class='slabel'>◌ &nbsp;Raw Extracted Text</div>",unsafe_allow_html=True)
#         st.text_area("",value=full_text,height=500,label_visibility="collapsed")
#         st.download_button("↓  Download Raw Text",data=full_text.encode(),file_name=f"raw_{uploaded_file.name.replace('.pdf','')}.txt",mime="text/plain")
# 
# else:
#     st.markdown("""
#     <div class='feat-grid'>
#         <div class='feat-card'><div class='fi'>✦</div><div class='ft'>Auto Summary</div><div class='fd'>Full summary the moment you upload</div></div>
#         <div class='feat-card'><div class='fi'>◈</div><div class='ft'>Key Insights</div><div class='fd'>7 critical insights with ratings</div></div>
#         <div class='feat-card'><div class='fi'>◎</div><div class='ft'>Smart Q&A</div><div class='fd'>Ask anything, get precise answers</div></div>
#         <div class='feat-card'><div class='fi'>◉</div><div class='ft'>Methodology</div><div class='fd'>Deep technical analysis</div></div>
#         <div class='feat-card'><div class='fi'>◎</div><div class='ft'>Gap Analysis</div><div class='fd'>Research gaps & future work</div></div>
#         <div class='feat-card'><div class='fi'>◇</div><div class='ft'>5 Citations</div><div class='fd'>APA, MLA, Chicago, BibTeX, IEEE</div></div>
#         <div class='feat-card'><div class='fi'>↓</div><div class='ft'>Download</div><div class='fd'>Full professional report export</div></div>
#         <div class='feat-card'><div class='fi'>⚡</div><div class='ft'>Groq Powered</div><div class='fd'>LLaMA 3.3 70B — free & fast</div></div>
#     </div>""",unsafe_allow_html=True)

from pyngrok import ngrok
import subprocess
import time

# Kill everything
ngrok.kill()
subprocess.run(["pkill", "-9", "-f", "ngrok"], capture_output=True)
subprocess.run(["pkill", "-9", "-f", "streamlit"], capture_output=True)
time.sleep(5)
print("✅ Cleared!")

import subprocess
subprocess.run(["pkill", "-9", "-f", "streamlit"], capture_output=True)

# Fix the model name
with open("app.py", "r") as f:
    content = f.read()

content = content.replace("llama3-70b-8192", "llama-3.3-70b-versatile")

with open("app.py", "w") as f:
    f.write(content)

print("✅ Model updated!")

import subprocess, time
from pyngrok import ngrok
ngrok.kill()  # kills local ngrok

subprocess.Popen([
    "streamlit", "run", "app.py",
    "--server.port=8501",
    "--server.headless=true"
])

time.sleep(8)
ngrok.set_auth_token("3Ajtb2xgc9p1aGsY31Gf3yhbjgi_7QakLtYz6nzRALdfyWxL8")
public_url = ngrok.connect(8501)
print("🚀 Your app:", public_url.public_url)

# import time
# while True:
#     time.sleep(60)

import urllib.request
try:
    urllib.request.urlopen("http://localhost:8501")
    print("✅ Streamlit is running!")
except Exception as e:
    print("❌ Streamlit not running yet:", e)

import subprocess
import time

# Kill everything first
subprocess.run(["pkill", "-9", "-f", "streamlit"], capture_output=True)
time.sleep(3)

# Start streamlit and capture output
process = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port=8501", "--server.headless=true"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

time.sleep(8)

# Read output to see what happened
stdout = process.stdout.read1(2048).decode()
stderr = process.stderr.read1(2048).decode()

print("STDOUT:", stdout)
print("STDERR:", stderr)
print("Process alive:", process.poll() is None)